### ISSUE TITLE
Error in events.js on t2-vm create on OSX 10.11

### ISSUE THREAD

**Issue by ujjwalt** [tessel/t2-vm#25]
```
Initializing VM...
? Choose a bridge interface (or hit enter) en0: Wi-Fi (AirPort)
Downloading image...
............................................................................................................................................................. downloaded ...
Creating VM...
Attaching to serial port: /Users/ujjwalt/.tessel/vm.port
Configuring VM...
events.js:85
     throw er; // Unhandled 'error' event
           ^
Error: connect ENOENT
   at exports._errnoException (util.js:746:11)
   at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

I'm using node 0.12.7 and npm 2.14.4 although I've tried both node 0.10 and 4.0 and nothing works.

**Comment by Student007** [comment]
I could bet you are working within a VM ?
https://github.com/Student007/t2-reference-VMs/blob/master/macosx/FAQ.md

**Comment by ujjwalt** [comment]
@Student007: You just lost the bet.

**Comment by Student007** [comment]
You won a :rabbit2: :laughing: did you install [VirtualBox](https://www.virtualbox.org) and [extension packages](https://www.virtualbox.org/wiki/Downloads) ?

**Comment by ujjwalt** [comment]
You win. I did not have the extension packages. But is this mentioned anywhere?

**Comment by ujjwalt** [comment]
Now will this work on Node 4.x?

**Comment by johnnyman727** [comment]
@ujjwalt that's a good question. Currently `t2-cli` isn't compatible with `node-usb` on Node 4.x but since it's a VM (and doesn't connect via USB), it might not have that issue.
